#!/usr/bin/env bash
#
#
VERSION="1.0.7"
sudo mkdir -p /usr/local/share/nexus
sudo chown $USER:$USER /usr/local/share/nexus
cp -f nexus-updater/*.html /usr/local/share/nexus
sudo cp -f nexus-updater/nexus-updater.desktop /usr/local/share/applications/
sudo cp -f nexus-updater/*.sh /usr/local/sbin/
sudo rm -f /usr/local/bin/nexus-updater.sh
#[ -f $HOME/.local/share/applications/updatepi.desktop ] && rm -f $HOME/.local/share/applications/updatepi.desktop
exit 0
